# Generated by Django 6.0.1 on 2026-06-23 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AquiferPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district_name', models.CharField(max_length=255)),
                ('grace_anomaly', models.FloatField()),
                ('avg_ndvi', models.FloatField()),
                ('avg_ndwi', models.FloatField()),
                ('target_recharge_vol', models.FloatField()),
                ('optimal_coordinates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquifer_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
