# Generated by Django 6.0.6 on 2026-06-25 06:05

import django.db.models.deletion
from django.db import migrations, models

# Temporary in-memory storage for migrations
_profile_roles_temp = {}

def save_old_roles(apps, schema_editor):
    global _profile_roles_temp
    UserProfile = apps.get_model('api', 'UserProfile')
    db_alias = schema_editor.connection.alias
    for p in UserProfile.objects.using(db_alias).all():
        _profile_roles_temp[p.id] = p.role

def restore_new_roles(apps, schema_editor):
    global _profile_roles_temp
    Role = apps.get_model('api', 'Role')
    UserProfile = apps.get_model('api', 'UserProfile')
    db_alias = schema_editor.connection.alias

    roles_data = [
        ('ADMIN', 'Administrator'),
        ('ANALYST', 'Research Analyst'),
        ('PLANNER', 'Planner'),
        ('GUEST', 'Guest Viewer'),
    ]
    role_map = {}
    for code, name in roles_data:
        r, _ = Role.objects.using(db_alias).get_or_create(code=code, defaults={'name': name})
        role_map[code] = r

    for profile_id, role_code in _profile_roles_temp.items():
        p = UserProfile.objects.using(db_alias).filter(id=profile_id).first()
        if p and role_code in role_map:
            p.role = role_map[role_code]
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aquiferplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RunPython(save_old_roles, elidable=True),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.role'),
        ),
        migrations.RunPython(restore_new_roles, elidable=True),
    ]
